dist: trusty
language: node_js
sudo: false

node_js:
  - "9.11.1"

before_install:
  - npm i -g npm@5.6.0

jobs:
  include:
    stage: test
    services:
      - docker
    before_install:
      - docker pull testcafe/testcafe
      - docker run testcafe/testcafe
    env:
      - INSTANCES=freds
    script: docker run -v -it testcafe/testcafe chrome *.ts
