dist: trusty
language: node_js
sudo: false

node_js:
  - "9.11.1"

before_install:
  - npm i -g npm@5.6.0

jobs:
  include:
    stage: test
    services:
      - docker
    before_install:
      - docker pull testcafe/testcafe
    script: docker run -v ${TRAVIS_BUILD_DIR}/tests:/tests -it testcafe/testcafe 'chromium --no-sandbox' tests/**/*.ts
